version: '3'
services:
  nuxt:
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - test=1
