version: '3'
services:
  nuxt:
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - ./app:/app:cached
      # exclude volumes
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
